#!/bin/bash
# NEXTFLOW TASK: SummaryFiles
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_date() {
    local ts=$(date +%s%3N); [[ $ts == *3N ]] && date +%s000 || echo $ts
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /home/carisdak/deepimpute_paper_scripts/speed_memory/work/b2/d6b96bb9895605f2c466e4da546d52/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /home/carisdak/deepimpute_paper_scripts/speed_memory/work/b2/d6b96bb9895605f2c466e4da546d52/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f time_SAVER_100_1.txt
    rm -f vmstats_SAVER_100_1.txt
    rm -f time_SAVER_100_2.txt
    rm -f vmstats_SAVER_100_2.txt
    rm -f time_SAVER_500_1.txt
    rm -f vmstats_SAVER_500_1.txt
    rm -f time_SAVER_500_2.txt
    rm -f vmstats_SAVER_500_2.txt
    rm -f time_magic_500_2.txt
    rm -f vmstats_magic_500_2.txt
    rm -f time_magic_500_1.txt
    rm -f vmstats_magic_500_1.txt
    rm -f time_magic_100_1.txt
    rm -f vmstats_magic_100_1.txt
    rm -f time_magic_100_2.txt
    rm -f vmstats_magic_100_2.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/63/878edad78d6283694422207c830cd9/time_SAVER_100_1.txt time_SAVER_100_1.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/63/878edad78d6283694422207c830cd9/vmstats_SAVER_100_1.txt vmstats_SAVER_100_1.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/44/f27f5e99e3ea51df9f78240865df7b/time_SAVER_100_2.txt time_SAVER_100_2.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/44/f27f5e99e3ea51df9f78240865df7b/vmstats_SAVER_100_2.txt vmstats_SAVER_100_2.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/49/db3593f8727410352b2c1cf5b276b6/time_SAVER_500_1.txt time_SAVER_500_1.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/49/db3593f8727410352b2c1cf5b276b6/vmstats_SAVER_500_1.txt vmstats_SAVER_500_1.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/d9/4c7744830161dc41405144637856d2/time_SAVER_500_2.txt time_SAVER_500_2.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/d9/4c7744830161dc41405144637856d2/vmstats_SAVER_500_2.txt vmstats_SAVER_500_2.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/4b/bc04b183db16085d5b66a10cee2c3c/time_magic_500_2.txt time_magic_500_2.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/4b/bc04b183db16085d5b66a10cee2c3c/vmstats_magic_500_2.txt vmstats_magic_500_2.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/9f/92518e26bcccd6581d3b025debc8e2/time_magic_500_1.txt time_magic_500_1.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/9f/92518e26bcccd6581d3b025debc8e2/vmstats_magic_500_1.txt vmstats_magic_500_1.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/61/7f9dae7619f37e358e087e6bc18d60/time_magic_100_1.txt time_magic_100_1.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/61/7f9dae7619f37e358e087e6bc18d60/vmstats_magic_100_1.txt vmstats_magic_100_1.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/41/11c84a065e2cf198cda0dcee80a740/time_magic_100_2.txt time_magic_100_2.txt
    ln -s /home/carisdak/deepimpute_paper_scripts/speed_memory/work/41/11c84a065e2cf198cda0dcee80a740/vmstats_magic_100_2.txt vmstats_magic_100_2.txt
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR1 USR2

    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/carisdak/deepimpute_paper_scripts/speed_memory/work/b2/d6b96bb9895605f2c466e4da546d52/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    local ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
